# Generated by Django 5.1.4 on 2025-04-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('stipend', models.CharField(max_length=50)),
                ('posted_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
